name: LightHouse

on:
  workflow_dispatch:
  issues:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: LightHouse Testing
      env:
        GHKEY: ${{ secrets.GH_TOKEN }}
      run: |
       npm install -g lighthouse
       sudo apt-get install xvfb
       Xvfb :7 -screen 0 1336x768x24 2>/dev/null &
       export DISPLAY=:7
       pip install requests
       pip install pyyaml
       python tool/Test.py
       python tool/Generate.py
       # ls
       # cat 1.json
    - name: File commit
      run: |
          git config --global user.email nineto0@163.com
          git config --global user.name Mlikiowa  
          git add test      
          git commit -m "Light HouseTest" -a		
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GH_TOKEN }}
# lighthouse https://nanaeo.cn --output html --output-path ./domain.json   
# cat domain.json    
