name: Testing

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install requirements 
      run: | 
        pip install selenium
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
        dpkg -i google-chrome-stable_current_amd64.deb
        apt-get -f install
    - name: Setting Environment
      run: |
        wget -O- https://intoli.com/install-google-chrome.sh | sh
    
